// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HttpClient is an autogenerated mock type for the HttpClient type
type HttpClient struct {
	mock.Mock
}

// ExecutePostRequest provides a mock function with given fields: ctx, url, payload
func (_m *HttpClient) ExecutePostRequest(ctx context.Context, url string, payload any) (string, error) {
	ret := _m.Called(ctx, url, payload)

	if len(ret) == 0 {
		panic("no return value specified for ExecutePostRequest")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any) (string, error)); ok {
		return rf(ctx, url, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, any) string); ok {
		r0 = rf(ctx, url, payload)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, any) error); ok {
		r1 = rf(ctx, url, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHttpClient creates a new instance of HttpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHttpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *HttpClient {
	mock := &HttpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
